"use client";

import { useState, useEffect, useCallback, useMemo } from "react";
import {
  format, addMonths, subMonths, startOfMonth, endOfMonth, eachDayOfInterval,
  isSameMonth, isToday, isPast, startOfDay, startOfWeek, endOfWeek,
} from "date-fns";
import { fr } from "date-fns/locale";
import {
  Loader2, Plus, Trash2, CalendarDays, AlertCircle, Sun,
  ChevronLeft, ChevronRight, X, Clock, Ban,
} from "lucide-react";
import { apiFetch } from "@/lib/api";
import {
  getDominantSlot, getDayConstraints, dateStr, toFrIdx, SLOT_COLORS,
  SLOT_TYPE_LABELS, displayType, formatSlotSummary, windowsForDay, findInvalidDays,
  FR_DAYS, type AvailabilitySlot,
} from "@/lib/availabilityConflicts";

const TYPE_LABELS: Record<string, string> = {
  specific: "Dates précises",
  range: "Plage de dates",
  recurring: "Jours récurrents",
};

const SECTION_LABEL: Record<string, string> = {
  hebergement: "Hébergement", restauration: "Restauration",
  transport: "Transport", guide: "Guidage", autre: "Autre",
};

const RESERVATION_STATUS_LABEL: Record<string, string> = {
  confirmed: "Confirmée", pending: "En attente", cancelled: "Annulée",
};

type AgendaReservation = {
  id: string;
  ref: string;
  status: string;
  date: string;
  start_time: string;
  end_time: string;
  title: string;
  traveler: string;
};

type IncomingReservation = {
  id: string;
  reservation_ref: string;
  status: string;
  total_price?: string | number;
  currency?: string;
  guideOffering?: { id: string; title: string } | null;
  offer?: { id: string; title: string } | null;
  guideOfferingSession?: { id: string; date: string | Date; start_time: string; end_time: string } | null;
  session?: { id: string; date: string | Date; start_time: string; end_time: string } | null;
  traveler?: { id: string; full_name: string } | null;
};

function normalizeReservations(list: IncomingReservation[]): AgendaReservation[] {
  const out: AgendaReservation[] = [];
  for (const r of list) {
    if (r.status === "cancelled") continue;
    const s = r.guideOfferingSession ?? r.session;
    if (!s?.date) continue;
    const d = typeof s.date === "string" ? s.date.slice(0, 10) : new Date(s.date).toISOString().slice(0, 10);
    out.push({
      id: r.id,
      ref: r.reservation_ref ?? r.id,
      status: r.status,
      date: d,
      start_time: (s.start_time ?? "").slice(0, 5),
      end_time: (s.end_time ?? "").slice(0, 5),
      title: r.guideOffering?.title ?? r.offer?.title ?? "Réservation",
      traveler: r.traveler?.full_name ?? "Voyageur",
    });
  }
  return out;
}

const DAY_MIN = 23 * 60 + 59;
const toMin = (t: string) => { const [h, m] = t.split(":").map(Number); return h * 60 + m; };

/** % of the day already taken, across all blocked windows */
function blockedPercent(day: Date, slots: AvailabilitySlot[]): number {
  const blockedMin = getDayConstraints(day, slots)
    .blockedWindows
    .reduce((sum, w) => sum + (toMin(w.end) - toMin(w.start)), 0);
  return Math.min(100, Math.round((blockedMin / DAY_MIN) * 100));
}

/** True for auto-slots generated by offers / collaborations (real reservations) */
function isReservationSlot(s: AvailabilitySlot): boolean {
  return s.label?.startsWith("[Offre]") ?? s.label?.startsWith("[Collab]") ?? false;
}

function getAllSlotsForDay(day: Date, slots: AvailabilitySlot[]): AvailabilitySlot[] {
  const ds   = dateStr(day);
  const wday = toFrIdx(day);
  return slots.filter((s) => {
    if (s.type === "specific")                  return s.dates?.includes(ds);
    if (s.type === "range" && s.start_date && s.end_date) {
      if (ds < s.start_date || ds > s.end_date) return false;
      return !s.days_of_week?.length || s.days_of_week.includes(wday);
    }
    if (s.type === "recurring" && s.days_of_week?.includes(wday)) {
      if (s.start_date && ds < s.start_date) return false;
      if (s.end_date   && ds > s.end_date)   return false;
      return true;
    }
    return false;
  });
}

function cleanLabel(s: AvailabilitySlot): { clean: string; kind: "collab" | "offre" | "manual"; section: string } {
  const label = s.label || "";
  if (label.startsWith("[Collab]")) {
    const rest = label.replace(/^\[Collab\]\s*/, "");
    const section = rest.match(/—\s*(\w+)$/)?.[1] ?? "";
    return { clean: rest.replace(/\s*—\s*\w+$/, "").trim(), kind: "collab", section };
  }
  if (label.startsWith("[Offre]")) {
    return { clean: label.replace(/^\[Offre\]\s*/, "").trim(), kind: "offre", section: "" };
  }
  return { clean: label, kind: "manual", section: "" };
}

interface AgendaManagerProps {
  userId: string;
}

export default function AgendaManager({ userId }: AgendaManagerProps) {
  const [slots, setSlots] = useState<AvailabilitySlot[]>([]);
  const [reservations, setReservations] = useState<AgendaReservation[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [saving, setSaving] = useState(false);
  const [showForm, setShowForm] = useState(false);
  const [currentDate, setCurrentDate] = useState(() => new Date());

  // Day detail popup
  const [popup, setPopup] = useState<{ date: Date; slots: AvailabilitySlot[]; reservations: AgendaReservation[] } | null>(null);
  const [deleting, setDeleting] = useState<string | null>(null);
  const [leaving, setLeaving] = useState<string | null>(null);

  // Form state
  const [type, setType] = useState<"specific" | "range" | "recurring">("recurring");
  const [dates, setDates] = useState("");
  const [startDate, setStartDate] = useState("");
  const [endDate, setEndDate] = useState("");
  const [daysOfWeek, setDaysOfWeek] = useState<string[]>([]);
  const [startTime, setStartTime] = useState("09:00");
  const [endTime, setEndTime] = useState("17:00");

  const fetchSlots = useCallback(() => {
    Promise.all([
      apiFetch<AvailabilitySlot[]>("/collaborations/availability").catch(() => [] as AvailabilitySlot[]),
      apiFetch<IncomingReservation[]>("/reservations/incoming").catch(() => [] as IncomingReservation[]),
    ])
      .then(([s, r]) => {
        setSlots(s);
        setReservations(normalizeReservations(r));
      })
      .catch(() => {})
      .finally(() => setLoading(false));
  }, []);

  useEffect(() => {
    if (userId) fetchSlots();
  }, [userId, fetchSlots]);

  const toggleDay = (i: number) => {
    setDaysOfWeek((prev) => {
      const idx = String(i);
      return prev.includes(idx)
        ? prev.filter((d) => d !== idx)
        : [...prev, idx];
    });
  };

  const openCreateForDay = (day: Date) => {
    setType("specific");
    setDates(dateStr(day));
    setShowForm(true);
  };

  const handleSave = async () => {
    setSaving(true);
    setError("");
    try {
      const timeSlots =
        startTime && endTime
          ? { "0": [{ start: startTime, end: endTime }] }
          : null;
      const body: any = {
        type,
        time_slots: timeSlots,
      };
      if (type === "specific") {
        body.dates = dates
          .split(",")
          .map((d) => d.trim())
          .filter(Boolean);
      } else if (type === "range") {
        body.start_date = startDate || null;
        body.end_date = endDate || null;
      } else if (type === "recurring") {
        body.days_of_week = daysOfWeek;
      }

      const candidate: Omit<AvailabilitySlot, "id"> = body;
      const invalid = findInvalidDays(candidate, slots);
      if (invalid.length > 0) {
        setError("Certaines dates/horaires sélectionnés sont déjà pris. Modifie ta sélection.");
        setSaving(false);
        return;
      }

      await apiFetch("/collaborations/availability", {
        method: "POST",
        body: JSON.stringify(body),
      });
      setShowForm(false);
      resetForm();
      fetchSlots();
    } catch (e: any) {
      setError(e.message || "Erreur lors de l'ajout du créneau");
    } finally {
      setSaving(false);
    }
  };

  const resetForm = () => {
    setDates("");
    setStartDate("");
    setEndDate("");
    setDaysOfWeek([]);
    setStartTime("09:00");
    setEndTime("17:00");
  };

  const handleDelete = async (id: string) => {
    if (!confirm("Supprimer ce créneau ?")) return;
    setDeleting(id);
    try {
      await apiFetch(`/collaborations/availability/${id}`, { method: "DELETE" });
      setSlots((prev) => prev.filter((s) => s.id !== id));
      setPopup((p) => p ? { ...p, slots: p.slots.filter((s) => s.id !== id) } : null);
    } catch (e: any) {
      setError(e.message || "Erreur lors de la suppression");
    } finally {
      setDeleting(null);
    }
  };

  const handleLeaveCollab = async (label: string) => {
    if (!confirm("Quitter cette collaboration ? Le créneau associé sera supprimé.")) return;
    setLeaving(label);
    try {
      await apiFetch("/collaborations/leave", {
        method: "PATCH",
        body: JSON.stringify({ slot_label: label }),
      });
      setSlots((prev) => prev.filter((s) => s.label !== label));
      setPopup(null);
      fetchSlots();
    } catch (e: any) {
      setError(e.message || "Impossible de quitter la collaboration.");
    } finally {
      setLeaving(null);
    }
  };

  // Calendar grid (6 weeks)
  const calStart = startOfWeek(startOfMonth(currentDate), { weekStartsOn: 1 });
  const calEnd   = endOfWeek(endOfMonth(currentDate),     { weekStartsOn: 1 });
  const calDays  = eachDayOfInterval({ start: calStart, end: calEnd });

  const reservationsByDate = useMemo(() => {
    const m = new Map<string, AgendaReservation[]>();
    for (const r of reservations) {
      const arr = m.get(r.date) ?? [];
      arr.push(r);
      m.set(r.date, arr);
    }
    return m;
  }, [reservations]);

  function handleDayClick(day: Date) {
    if (isPast(startOfDay(day)) && !isToday(day)) return;
    const ds = dateStr(day);
    const daySlots = getAllSlotsForDay(day, slots);
    const dayRes = reservationsByDate.get(ds) ?? [];
    if (daySlots.length > 0 || dayRes.length > 0) {
      setPopup({ date: day, slots: daySlots, reservations: dayRes });
    } else {
      openCreateForDay(day);
    }
  }

  function dayClass(day: Date): { cls: string; fillPct: number | null } {
    const past  = isPast(startOfDay(day)) && !isToday(day);
    const today = isToday(day);
    const inM   = isSameMonth(day, currentDate);

    let base = "relative w-full aspect-square rounded-xl text-xs font-bold flex flex-col items-center justify-center select-none transition-all ";
    if (!inM) base += "opacity-30 ";
    if (past) { base += "text-slate-300 cursor-default "; return { cls: base.trim(), fillPct: null }; }
    base += "cursor-pointer ";

    const ring = today ? " ring-2 ring-emerald-400 ring-offset-1" : "";
    const constraints = getDayConstraints(day, slots);
    const dom = getDominantSlot(day, slots);

    // ── Journée complète : créneau [Offre]/[Collab] sur toute la journée,
    //    ou horaires couvrant 100% du jour → barré + icône Ban
    if (constraints.isFullyBlocked) {
      // Créneau manuel sur toute la journée → afficher la couleur du type
      if (dom && !isReservationSlot(dom)) {
        const c = SLOT_COLORS[displayType(dom)];
        return { cls: (base + `${c.bg} ${c.text}${ring}`).trim(), fillPct: null };
      }
      return { cls: (base + "bg-slate-100 text-slate-400 line-through cursor-not-allowed").trim(), fillPct: null };
    }

    if (constraints.blockedWindows.length > 0) {
      // ── Se remplit en rouge : jour partiellement pris
      const pct = blockedPercent(day, slots);
      if (pct >= 100) {
        return { cls: (base + "bg-slate-100 text-slate-400 line-through cursor-not-allowed").trim(), fillPct: null };
      }
      return { cls: (base + `text-slate-700${ring}`).trim(), fillPct: pct };
    }

    // ── Créneau dominant : couleur du type (Date unique / Plage / Récurrent)
    if (dom) {
      const c = SLOT_COLORS[displayType(dom)];
      return { cls: (base + `${c.bg} ${c.text}${ring}`).trim(), fillPct: null };
    }

    return { cls: (base + `hover:bg-emerald-50 text-slate-600${ring}`).trim(), fillPct: null };
  }

  if (loading) {
    return (
      <div className="flex items-center justify-center py-16">
        <Loader2 className="w-6 h-6 animate-spin text-emerald-500" />
      </div>
    );
  }

  return (
    <div className="space-y-5">
      {error && (
        <div className="flex items-start gap-3 text-sm text-red-600 bg-red-50 border border-red-200 p-3 rounded-xl">
          <AlertCircle className="w-5 h-5 shrink-0 mt-0.5" />
          <span>{error}</span>
          <button onClick={() => setError("")} className="ml-auto text-red-400 hover:text-red-600">✕</button>
        </div>
      )}

      {/* Header */}
      <div className="flex items-center justify-between flex-wrap gap-3">
        <div>
          <h3 className="font-extrabold text-slate-800 text-base">Mon agenda de disponibilité</h3>
          <p className="text-xs text-slate-500">
            Cliquez sur un jour pour voir ou ajouter vos disponibilités.
          </p>
        </div>
        {!showForm && (
          <button
            onClick={() => setShowForm(true)}
            className="flex items-center gap-2 px-4 py-2 rounded-xl bg-emerald-600 text-white text-sm font-semibold hover:bg-emerald-700"
          >
            <Plus size={16} /> Ajouter un créneau
          </button>
        )}
      </div>

      {/* Navigation mois */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <button
            onClick={() => setCurrentDate((d) => subMonths(d, 1))}
            className="w-9 h-9 rounded-xl border border-slate-200 flex items-center justify-center text-slate-500 hover:bg-slate-50"
            aria-label="Mois précédent"
          >
            <ChevronLeft size={16} />
          </button>
          <button
            onClick={() => setCurrentDate((d) => addMonths(d, 1))}
            className="w-9 h-9 rounded-xl border border-slate-200 flex items-center justify-center text-slate-500 hover:bg-slate-50"
            aria-label="Mois suivant"
          >
            <ChevronRight size={16} />
          </button>
          <p className="text-sm font-extrabold text-slate-800 capitalize ml-1">
            {format(currentDate, "MMMM yyyy", { locale: fr })}
          </p>
        </div>
        <button
          onClick={() => setCurrentDate(new Date())}
          className="text-xs font-bold text-emerald-600 hover:text-emerald-700"
        >
          Aujourd&apos;hui
        </button>
      </div>

      {/* Calendrier */}
      <div className="bg-white rounded-3xl border border-slate-100/80 shadow-sm overflow-hidden max-w-3xl">
        <div className="grid grid-cols-7 bg-slate-50 border-b border-slate-100">
          {FR_DAYS.map((d) => (
            <div key={d} className="text-center text-[10px] font-extrabold text-slate-400 uppercase py-3 tracking-wider">{d}</div>
          ))}
        </div>
        <div className="grid grid-cols-7 gap-0.5 p-2">
          {calDays.map((day) => {
            const past = isPast(startOfDay(day)) && !isToday(day);
            const ds = dateStr(day);
            const daySlots = getAllSlotsForDay(day, slots);
            const dayRes = reservationsByDate.get(ds) ?? [];
            const { cls, fillPct } = dayClass(day);
            const trulyBlocked = cls.includes("line-through");
            return (
              <button
                key={day.toISOString()}
                type="button"
                onClick={() => handleDayClick(day)}
                disabled={past || trulyBlocked}
                title={!past ? (daySlots[0]?.label || (dayRes.length ? `${dayRes.length} réservation(s)` : undefined)) : undefined}
                className={cls}
                style={fillPct !== null ? { background: `conic-gradient(#f87171 0% ${fillPct}%, #a7f3d0 ${fillPct}% 100%)` } : undefined}
              >
                <span className="leading-none drop-shadow-[0_1px_1px_rgba(255,255,255,0.6)]">{format(day, "d")}</span>
                {trulyBlocked && !past && (
                  <Ban size={10} className="absolute top-1 right-1 text-slate-300" />
                )}
                {dayRes.length > 0 && !past && (
                  <span className="absolute top-1 left-1 flex gap-0.5">
                    <span className="w-1.5 h-1.5 rounded-full bg-violet-500 ring-1 ring-white" />
                  </span>
                )}
                {daySlots.length > 0 && !past && fillPct === null && !trulyBlocked && (
                  <span className="absolute bottom-1 left-1/2 -translate-x-1/2 flex gap-0.5">
                    {daySlots.slice(0, 3).map((s, i) => (
                      <span key={i} className={`w-1 h-1 rounded-full ${SLOT_COLORS[displayType(s)]?.dot}`} />
                    ))}
                  </span>
                )}
              </button>
            );
          })}
        </div>

        {/* Légende */}
        <div className="px-4 py-3 border-t border-slate-100 flex flex-wrap gap-3">
          {(["specific", "range", "recurring"] as const).map((t) => (
            <div key={t} className="flex items-center gap-1.5">
              <div className={`w-3 h-3 rounded-sm ${SLOT_COLORS[t].dot}`} />
              <span className="text-[10px] font-bold text-slate-400">{SLOT_TYPE_LABELS[t]}</span>
            </div>
          ))}
          <div className="flex items-center gap-1.5">
            <span className="w-3 h-3 rounded-full shrink-0"
              style={{ background: "conic-gradient(#f87171 0% 40%, #a7f3d0 40% 100%)" }} />
            <span className="text-[10px] font-bold text-slate-400">Se remplit en rouge à mesure que le jour se prend</span>
          </div>
          <div className="flex items-center gap-1.5">
            <Ban size={11} className="text-slate-300" />
            <span className="text-[10px] font-bold text-slate-400">Journée complète</span>
          </div>
          <div className="flex items-center gap-1.5">
            <span className="w-3 h-3 rounded-full bg-violet-500" />
            <span className="text-[10px] font-bold text-slate-400">Réservation</span>
          </div>
        </div>
      </div>

      {/* Add form */}
      {showForm && (
        <div className="bg-white border border-emerald-100 rounded-2xl p-5 space-y-4">
          <div className="flex items-center justify-between">
            <p className="text-sm font-bold text-slate-800">Nouveau créneau</p>
            <button onClick={() => setShowForm(false)} className="text-slate-400 hover:text-slate-600 text-sm font-semibold">
              Annuler
            </button>
          </div>

          {/* Type selector */}
          <div className="grid grid-cols-3 gap-2">
            {(["specific", "range", "recurring"] as const).map((t) => (
              <button
                key={t}
                onClick={() => setType(t)}
                className={`p-2.5 rounded-xl text-center text-xs font-medium border transition ${
                  type === t
                    ? "bg-emerald-50 border-emerald-300 text-emerald-700"
                    : "border-slate-200 text-slate-600 hover:bg-slate-50"
                }`}
              >
                {TYPE_LABELS[t]}
              </button>
            ))}
          </div>

          {type === "specific" && (
            <div>
              <label className="block text-sm font-semibold text-slate-700 mb-2">
                Dates (séparées par des virgules, format AAAA-MM-JJ)
              </label>
              <input
                type="text"
                value={dates}
                onChange={(e) => setDates(e.target.value)}
                placeholder="2026-08-10, 2026-08-11"
                className="w-full px-4 py-2.5 rounded-xl border border-slate-200 focus:border-emerald-400 focus:ring-2 focus:ring-emerald-100 outline-none text-sm"
              />
            </div>
          )}

          {type === "range" && (
            <div className="grid grid-cols-2 gap-3">
              <div>
                <label className="block text-sm font-semibold text-slate-700 mb-2">Du</label>
                <input
                  type="date"
                  value={startDate}
                  onChange={(e) => setStartDate(e.target.value)}
                  className="w-full px-4 py-2.5 rounded-xl border border-slate-200 focus:border-emerald-400 focus:ring-2 focus:ring-emerald-100 outline-none text-sm"
                />
              </div>
              <div>
                <label className="block text-sm font-semibold text-slate-700 mb-2">Au</label>
                <input
                  type="date"
                  value={endDate}
                  onChange={(e) => setEndDate(e.target.value)}
                  className="w-full px-4 py-2.5 rounded-xl border border-slate-200 focus:border-emerald-400 focus:ring-2 focus:ring-emerald-100 outline-none text-sm"
                />
              </div>
            </div>
          )}

          {type === "recurring" && (
            <div>
              <label className="block text-sm font-semibold text-slate-700 mb-2">
                Jours de la semaine
              </label>
              <div className="flex flex-wrap gap-2">
                {FR_DAYS.map((d, i) => {
                  const active = daysOfWeek.includes(String(i));
                  return (
                    <button
                      key={i}
                      onClick={() => toggleDay(i)}
                      className={`w-10 h-10 rounded-xl text-xs font-bold border transition ${
                        active
                          ? "bg-emerald-600 text-white border-emerald-600"
                          : "border-slate-200 text-slate-600 hover:bg-slate-50"
                      }`}
                    >
                      {d}
                    </button>
                  );
                })}
              </div>
            </div>
          )}

          {/* Time range */}
          <div className="grid grid-cols-2 gap-3">
            <div>
              <label className="block text-sm font-semibold text-slate-700 mb-2">Début</label>
              <input
                type="time"
                value={startTime}
                onChange={(e) => setStartTime(e.target.value)}
                className="w-full px-4 py-2.5 rounded-xl border border-slate-200 focus:border-emerald-400 focus:ring-2 focus:ring-emerald-100 outline-none text-sm"
              />
            </div>
            <div>
              <label className="block text-sm font-semibold text-slate-700 mb-2">Fin</label>
              <input
                type="time"
                value={endTime}
                onChange={(e) => setEndTime(e.target.value)}
                className="w-full px-4 py-2.5 rounded-xl border border-slate-200 focus:border-emerald-400 focus:ring-2 focus:ring-emerald-100 outline-none text-sm"
              />
            </div>
          </div>

          <button
            onClick={handleSave}
            disabled={saving}
            className="w-full py-2.5 rounded-xl bg-emerald-600 text-white text-sm font-semibold hover:bg-emerald-700 disabled:opacity-50 flex items-center justify-center gap-2"
          >
            {saving ? <Loader2 className="w-4 h-4 animate-spin" /> : <Plus size={16} />}
            Ajouter
          </button>
        </div>
      )}

      {/* Empty state */}
      {slots.length === 0 && reservations.length === 0 && !showForm && (
        <div className="bg-white rounded-3xl border border-slate-100/80 shadow-sm p-12 text-center">
          <div className="w-14 h-14 bg-emerald-50 rounded-2xl flex items-center justify-center mx-auto mb-4">
            <CalendarDays size={24} className="text-emerald-400" />
          </div>
          <p className="text-slate-800 font-extrabold text-base mb-1">Aucun créneau</p>
          <p className="text-slate-400 text-sm">
            Ajoutez vos disponibilités pour que le système détecte les conflits avec vos collaborations.
          </p>
        </div>
      )}

      {/* Popup jour */}
      {popup && (popup.slots.length > 0 || (popup.reservations?.length ?? 0) > 0) && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm p-4"
          onClick={() => setPopup(null)}>
          <div className="bg-white rounded-3xl w-full max-w-sm shadow-2xl p-5"
            onClick={(e) => e.stopPropagation()}>
            <div className="flex items-center justify-between mb-4">
              <div>
                <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest capitalize">
                  {format(popup.date, "EEEE", { locale: fr })}
                </p>
                <p className="text-xl font-extrabold text-slate-800">
                  {format(popup.date, "dd MMMM yyyy", { locale: fr })}
                </p>
              </div>
              <button type="button" onClick={() => setPopup(null)}
                className="w-8 h-8 rounded-full bg-slate-100 hover:bg-slate-200 flex items-center justify-center transition-colors">
                <X size={16} className="text-slate-500" />
              </button>
            </div>
            <div className="space-y-2">
              {(popup.reservations ?? []).map((r) => (
                <div key={r.id} className="flex items-center gap-3 p-3 rounded-xl border bg-violet-50 border-violet-200">
                  <span className="w-8 h-8 rounded-lg bg-violet-100 text-violet-600 flex items-center justify-center shrink-0">
                    <CalendarDays size={16} />
                  </span>
                  <div className="flex-1 min-w-0">
                    <span className="inline-block text-[10px] font-black px-2 py-0.5 rounded-full bg-violet-100 text-violet-700 mb-1">
                      Réservation · {RESERVATION_STATUS_LABEL[r.status] ?? r.status}
                    </span>
                    <p className="text-xs font-extrabold mb-0.5 truncate text-violet-800">{r.title}</p>
                    <p className="flex items-center gap-1.5 text-xs font-bold text-violet-700">
                      <Clock size={10} className="shrink-0 opacity-60" />
                      {r.start_time.replace(":", "h")}–{r.end_time.replace(":", "h")}
                    </p>
                    <p className="mt-0.5 text-[10px] text-violet-500 font-medium truncate">👤 {r.traveler} · {r.ref}</p>
                  </div>
                </div>
              ))}
              {popup.slots.map((s) => {
                const c = SLOT_COLORS[displayType(s)];
                const windows = windowsForDay(s, popup.date);
                const { clean, kind, section } = cleanLabel(s);
                const isCollabSlot = kind === "collab";
                const isOfferSlot = kind === "offre";
                return (
                  <div key={s.id} className={`flex items-center gap-3 p-3 rounded-xl border ${
                    isCollabSlot ? "bg-emerald-50 border-emerald-200"
                    : isOfferSlot ? "bg-violet-50 border-violet-200"
                    : `${c.bg} ${c.border}`
                  }`}>
                    <span className={`w-8 h-8 rounded-lg flex items-center justify-center shrink-0 ${
                      isCollabSlot ? "bg-emerald-100 text-emerald-600" : isOfferSlot ? "bg-violet-100 text-violet-600" : c.bg
                    }`}>
                      {isCollabSlot ? <Sun size={16} /> : isOfferSlot ? <CalendarDays size={16} /> : s.type === "recurring" ? <Sun size={16} /> : <CalendarDays size={16} />}
                    </span>

                    <div className="flex-1 min-w-0">
                      {isCollabSlot ? (
                        <span className="inline-block text-[10px] font-black px-2 py-0.5 rounded-full bg-emerald-100 text-emerald-700 mb-1">
                          Offre collaborative · {SECTION_LABEL[section] ?? section}
                        </span>
                      ) : isOfferSlot ? (
                        <span className="inline-block text-[10px] font-black px-2 py-0.5 rounded-full bg-violet-100 text-violet-700 mb-1">
                          Mon offre
                        </span>
                      ) : (
                        <span className={`inline-block text-[10px] font-black px-2 py-0.5 rounded-full mb-1 bg-white/60 ${c.text}`}>
                          {SLOT_TYPE_LABELS[displayType(s)]}
                        </span>
                      )}

                      {clean && (
                        <p className={`text-xs font-extrabold mb-0.5 truncate ${
                          isCollabSlot ? "text-emerald-800" : isOfferSlot ? "text-violet-800" : c.text
                        }`}>{clean}</p>
                      )}

                      <p className={`text-xs opacity-70 ${isCollabSlot ? "text-emerald-700" : isOfferSlot ? "text-violet-600" : c.text}`}>
                        {formatSlotSummary(s)}
                      </p>
                      {windows?.length ? (
                        <div className="mt-1 space-y-0.5">
                          {windows.map((w, i) => (
                            <div key={i} className={`flex items-center gap-1.5 text-xs font-bold ${
                              isCollabSlot ? "text-emerald-700" : isOfferSlot ? "text-violet-700" : c.text
                            }`}>
                              <Clock size={10} className="shrink-0 opacity-60" />
                              {w.start.replace(":", "h")}–{w.end.replace(":", "h")}
                            </div>
                          ))}
                        </div>
                      ) : (
                        <p className={`flex items-center gap-1 text-xs font-medium mt-1 opacity-60 ${
                          isCollabSlot ? "text-emerald-600" : isOfferSlot ? "text-violet-500" : c.text
                        }`}>
                          <Clock size={10} className="shrink-0" />Toute la journée
                        </p>
                      )}

                      {isCollabSlot && (
                        <p className="mt-1 text-[10px] text-emerald-600 font-medium">
                          Créneau réservé · offre collaborative
                        </p>
                      )}
                      {isOfferSlot && (
                        <p className="mt-1 text-[10px] text-violet-500 font-medium">
                          Créneau lié à votre offre
                        </p>
                      )}
                    </div>

                    {/* Action : quitter la collaboration (créneau [Collab]) */}
                    {isCollabSlot ? (
                      <button
                        type="button"
                        onClick={() => handleLeaveCollab(s.label!)}
                        disabled={leaving === s.label}
                        className="text-[10px] font-bold px-2 py-1.5 rounded-lg border border-emerald-300 text-emerald-600 hover:bg-emerald-100 transition-all disabled:opacity-50 shrink-0"
                      >
                        {leaving === s.label ? "…" : "Quitter"}
                      </button>
                    ) : (
                      !isOfferSlot && (
                        <button
                          type="button"
                          onClick={() => handleDelete(s.id)}
                          disabled={deleting === s.id}
                          className="w-7 h-7 rounded-lg border border-slate-200 flex items-center justify-center text-slate-400 hover:text-red-600 hover:bg-red-50 transition-all disabled:opacity-50 shrink-0"
                        >
                          {deleting === s.id
                            ? <div className="w-3 h-3 rounded-full border border-slate-400 border-t-transparent animate-spin" />
                            : <Trash2 size={13} />}
                        </button>
                      )
                    )}
                  </div>
                );
              })}
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
